namespace: ecuaalejo2013-dev
name: cmtx-mongo
image: bitnami/mongodb:7.0
storage: 1Gi
port: 27017
secretName: cmtx-mongo-credentials
credentials:
  username: cmtx_user
  password: cmtx_pass_123
  database: cmtxdb
resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi