namespace: ecuaalejo2013-dev
name: cmtx-mongo
image: registry.access.redhat.com/rhscl/mongodb-36-rhel7
port: 27017
secretName: cmtx-mongo-credentials
credentials:
  username: cmtx_user
  password: cmtx_pass_123
  database: cmtxdb
persistence:
  enabled: false      # usa PVC s√≥lo cuando el cluster tenga storage disponible
  size: 1Gi
  storageClass: gp3
resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi
