apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.credentials.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.credentials.password }}
  MONGO_INITDB_DATABASE:      {{ .Values.credentials.database }}