apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.name }}
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: {{ .Values.name }} }
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/part-of: cmtx
    spec:
      securityContext: { fsGroup: 1001 }
      containers:
      - name: mongodb
        image: {{ .Values.image }}
        ports: [{ containerPort: {{ .Values.port }} }]
        envFrom:
        - secretRef: { name: {{ .Values.secretName }} }
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
        resources: {{- toYaml .Values.resources | nindent 10 }}
  volumeClaimTemplates:
  - metadata: { name: data }
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources: { requests: { storage: {{ .Values.storage }} } }