apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.credentials.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.credentials.password }}
  MONGO_INITDB_DATABASE:      {{ .Values.credentials.database }}
  MONGODB_USER:               {{ .Values.credentials.username }}
  MONGODB_PASSWORD:           {{ .Values.credentials.password }}
  MONGODB_DATABASE:           {{ .Values.credentials.database }}
  MONGODB_ADMIN_PASSWORD:     {{ .Values.credentials.password }}
